/**
 * Source injected into the page's main world.
 *
 * The web app is remote and `contextIsolation` is on, so the preload cannot
 * reach the page's own `navigator.mediaDevices`. We inject this instead: it
 * wraps getDisplayMedia and, when the main process captured a specific
 * application, swaps the system-wide audio track for that app's audio, and
 * swaps a window share's video track for one fed by native GPU-downscaled
 * capture (see native/win-capture and src/native/screenCapture.ts).
 *
 * The web app needs no changes and cannot tell the difference -- it still just
 * receives a MediaStream with one video and one audio track.
 *
 * Written as a plain string (no backticks, no template placeholders) so it
 * survives being handed to executeJavaScript verbatim.
 */
export const APP_AUDIO_PATCH = [
  "(() => {",
  "  const bridge = window.native && window.native.appAudio;",
  "  const screenCaptureBridge = window.native && window.native.screenCapture;",
  "",
  "  // The page console is filtered below error level (see window.ts), so which",
  "  // video path a share took -- and why, on fallback -- is reported through",
  "  // here instead, straight into app-audio.log.",
  "  const logPage = (msg) => {",
  "    try { console.log('[stoat]', msg); } catch (e) { /* noop */ }",
  "    try { if (screenCaptureBridge && screenCaptureBridge.log) screenCaptureBridge.log(msg); } catch (e) { /* noop */ }",
  "  };",
  "",
  "  if (window.__stoatAppAudioPatched) {",
  "    // The main process logs 'screen share patch injected' unconditionally",
  "    // on every executeJavaScript call, so without this line a duplicate",
  "    // injection reads exactly like the smoking gun for the session-overlap",
  "    // bug this file used to have -- log it explicitly so it stops looking",
  "    // like a mystery.",
  "    logPage('patch already installed; skipping');",
  "    return;",
  "  }",
  "  if (!bridge || !navigator.mediaDevices) return;",
  "  window.__stoatAppAudioPatched = true;",
  "",
  "  const WORKLET = [",
  "    'class PcmPlayer extends AudioWorkletProcessor {',",
  "    '  constructor() {',",
  "    '    super();',",
  "    '    this.queue = []; this.offset = 0;',",
  "    '    this.trims = 0;',",
  "    '    this.lastReport = 0;',",
  "    '    this.lastReportedTrims = 0;',",
  "    '    this.port.onmessage = (e) => {',",
  "    '      if (e.data === 0) { this.queue = []; this.offset = 0; return; }',",
  "    '      this.queue.push(e.data);',",
  "    '      let total = 0;',",
  "    '      for (let i = 0; i < this.queue.length; i++) total += this.queue[i].l.length;',",
  "    '      while (total > 24000 && this.queue.length > 1) {',",
  "    '        total -= this.queue.shift().l.length; this.offset = 0;',",
  "    '        this.trims++;',",
  "    '      }',",
  "    '    };',",
  "    '  }',",
  "    '  queueFrames() {',",
  "    '    let total = 0;',",
  "    '    for (let i = 0; i < this.queue.length; i++) total += this.queue[i].l.length;',",
  "    '    return Math.max(0, total - this.offset);',",
  "    '  }',",
  "    '  process(inputs, outputs) {',",
  "    '    const out = outputs[0];',",
  "    '    const L = out[0]; const R = out[1] || out[0];',",
  "    '    let i = 0;',",
  "    '    while (i < L.length) {',",
  "    '      if (!this.queue.length) { L.fill(0, i); R.fill(0, i); break; }',",
  "    '      const head = this.queue[0];',",
  "    '      const avail = head.l.length - this.offset;',",
  "    '      const n = Math.min(avail, L.length - i);',",
  "    '      L.set(head.l.subarray(this.offset, this.offset + n), i);',",
  "    '      R.set(head.r.subarray(this.offset, this.offset + n), i);',",
  "    '      i += n; this.offset += n;',",
  "    '      if (this.offset >= head.l.length) { this.queue.shift(); this.offset = 0; }',",
  "    '    }',",
  "    '    // Checked every ~5s, but only actually posted when it is interesting --',",
  "    '    // trims changed since the last report, or the queue is sitting close to',",
  "    '    // the 24000-frame (500ms) trim threshold -- so a healthy share stays',",
  "    '    // quiet. This is the direct, measured signal for the robotic-and-delayed',",
  "    '    // failure mode: a queue pinned near that threshold with trims climbing',",
  "    '    // IS that state. Posting unconditionally made app-audio.log grow for the',",
  "    '    // whole life of every share, and the 512KB cap truncates by deleting the',",
  "    '    // entire file -- including the \"capturing include pid N\" lines that are',",
  "    '    // the only evidence that matters -- so silence when nothing changed is',",
  "    '    // load-bearing, not cosmetic.',",
  "    '    if (currentTime - this.lastReport >= 5) {',",
  "    '      this.lastReport = currentTime;',",
  "    '      const frames = this.queueFrames();',",
  "    '      const trimsChanged = this.trims !== this.lastReportedTrims;',",
  "    '      if (trimsChanged || frames > 18000) {',",
  "    '        this.lastReportedTrims = this.trims;',",
  "    '        this.port.postMessage({ queueFrames: frames, trims: this.trims });',",
  "    '      }',",
  "    '    }',",
  "    '    return true;',",
  "    '  }',",
  "    '}',",
  "    'registerProcessor(\"pcm-player\", PcmPlayer);'",
  "  ].join('\\n');",
  "",
  "  // Per-session ownership, replacing what used to be module-scoped",
  "  // singletons (ctx/node/dest/unsubscribe) shared by every call to",
  "  // getDisplayMedia. With a singleton, the chunk subscription closure read",
  "  // the *current* module-level 'node', and teardown() acted on 'whatever is",
  "  // currently in those variables' -- so when two shares overlapped (see",
  "  // changeScreenShareSource in for-web, which deliberately acquires the new",
  "  // source before tearing down the old one), whichever teardown ran last",
  "  // won, and it tore down resources -- and stopped the native mixer behind",
  "  // -- resources it did not own. A late teardown from the previous share",
  "  // silently killed the current one.",
  "  //",
  "  // Each getDisplayMedia call now builds its own session object and the",
  "  // chunk closure captures *that* object, not an outer variable. A stale",
  "  // subscription becomes structurally inert: once its own session is marked",
  "  // dead it cannot deliver into a node it no longer owns.",
  "  //",
  "  // Deliberately NOT fixed by tearing down the previous share synchronously",
  "  // at the top of this function, before starting the new one: main already",
  "  // stops the previous share's native audio and video capture the instant a",
  "  // new getDisplayMedia request arrives -- before the picker even reaches",
  "  // the renderer (see native/window.ts's stopAppAudio()/stopScreenCapture()",
  "  // calls ahead of both desktopCapturer.getSources() and the armed",
  "  // re-acquire path) -- so a cancelled picker already leaves the previous",
  "  // share dead on Windows; teardown-first here would buy nothing on that",
  "  // front. What it WOULD do is destroy this share's own AudioContext and",
  "  // worklet graph before the incoming share is ready to use them, and it",
  "  // would re-introduce exactly the kind of ordering assumption ('teardown",
  "  // always happens strictly before the next build') that this per-session",
  "  // design exists to eliminate. Ownership is tracked explicitly instead (see",
  "  // 'generation' below), so nothing has to assume anything about order.",
  "  let sessionCounter = 0;",
  "  let activeSession = null;",
  "",
  "  // Single ownership token shared by audio and video, claimed synchronously",
  "  // by the getDisplayMedia wrapper immediately after the underlying native",
  "  // call resolves -- see the long comment at that call site for why it has",
  "  // to happen exactly there, before any further await. Every stop()/",
  "  // bridge.stop() guard below tests this one generation instead of the two",
  "  // separate, later-claimed mechanisms (an audio 'session' object identity,",
  "  // a video-only owner counter) this file used to have; a stale attempt from",
  "  // an older generation can build a session or a video track just fine, but",
  "  // can never stop a newer generation's native capture, because by then",
  "  // 'currentGeneration' no longer matches the token it captured.",
  "  let generationCounter = 0;",
  "  let currentGeneration = 0;",
  "",
  "  const buildSession = async (state, generation) => {",
  "    const s = { id: ++sessionCounter, generation: generation, ctx: null, node: null, dest: null, unsub: null, track: null, dead: false };",
  "    try {",
  "      s.ctx = new AudioContext({ sampleRate: state.sampleRate || 48000 });",
  "      const url = URL.createObjectURL(new Blob([WORKLET], { type: 'application/javascript' }));",
  "      try { await s.ctx.audioWorklet.addModule(url); } finally { URL.revokeObjectURL(url); }",
  "      s.node = new AudioWorkletNode(s.ctx, 'pcm-player', { outputChannelCount: [2] });",
  "      s.dest = s.ctx.createMediaStreamDestination();",
  "      s.node.connect(s.dest);",
  "      if (s.ctx.state === 'suspended') { try { await s.ctx.resume(); } catch (e) { /* noop */ } }",
  "",
  "      s.node.port.onmessage = (e) => {",
  "        if (!e || !e.data || typeof e.data !== 'object' || !('queueFrames' in e.data)) return;",
  "        logPage('audio: session #' + s.id + ' queueFrames=' + e.data.queueFrames + ' trims=' + e.data.trims);",
  "      };",
  "",
  "      s.unsub = bridge.onChunk((chunk) => {",
  "        // Reads this session's own node, captured by closure -- never a",
  "        // shared outer variable. Once dead, this is a no-op: a stale",
  "        // subscription that outlives its session cannot deliver into a node",
  "        // it no longer owns.",
  "        if (s.dead || !s.node) return;",
  "        const bytes = chunk instanceof Uint8Array ? chunk : new Uint8Array(chunk);",
  "        const frames = (bytes.byteLength >> 1) >> 1;",
  "        if (!frames) return;",
  "        const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);",
  "        const l = new Float32Array(frames);",
  "        const r = new Float32Array(frames);",
  "        for (let i = 0; i < frames; i++) {",
  "          l[i] = view.getInt16(i * 4, true) / 32768;",
  "          r[i] = view.getInt16(i * 4 + 2, true) / 32768;",
  "        }",
  "        s.node.port.postMessage({ l: l, r: r }, [l.buffer, r.buffer]);",
  "      });",
  "",
  "      s.track = s.dest.stream.getAudioTracks()[0] || null;",
  "    } catch (e) {",
  "      // Partial construction: clean up directly and rethrow so the caller",
  "      // logs and stays silent.",
  "      s.dead = true;",
  "      if (s.unsub) { try { s.unsub(); } catch (e2) { /* noop */ } }",
  "      if (s.node) { try { s.node.disconnect(); } catch (e2) { /* noop */ } }",
  "      if (s.dest) { try { s.dest.disconnect(); } catch (e2) { /* noop */ } }",
  "      if (s.ctx) { s.ctx.close().catch(() => {}); }",
  "      throw e;",
  "    }",
  "    let listeners = '?';",
  "    try { listeners = bridge.listenerCount(); } catch (e) { /* noop */ }",
  "    logPage('audio: session #' + s.id + ' built (chunk listeners=' + listeners + ')');",
  "    return s;",
  "  };",
  "",
  "  // Idempotent per session object: calling this twice on the same object --",
  "  // once when a newer session replaces it, once from its own video track's",
  "  // late 'ended'/stop() -- is a no-op the second time, and it only ever",
  "  // touches the resources that specific object owns.",
  "  const closeSession = (s) => {",
  "    if (!s || s.dead) return;",
  "    s.dead = true;",
  "    if (s.unsub) { try { s.unsub(); } catch (e) { /* noop */ } }",
  "    if (s.node) { try { s.node.disconnect(); } catch (e) { /* noop */ } }",
  "    if (s.dest) { try { s.dest.disconnect(); } catch (e) { /* noop */ } }",
  "    if (s.ctx) { s.ctx.close().catch(() => {}); }",
  "    // Only stop the native mixer/IPC producer -- and only drop the module's",
  "    // reference to it -- when this session's generation is still the current",
  "    // one. This is what stops a late close (from an overlapping, superseded",
  "    // share) from killing a newer share's capture: the generation this",
  "    // session was tagged with was claimed synchronously right after its own",
  "    // getDisplayMedia call resolved (see the wrapper below), so once a newer",
  "    // call has claimed a later generation, this comparison fails and",
  "    // bridge.stop() never fires, no matter how late this runs.",
  "    if (s.generation === currentGeneration) {",
  "      try { bridge.stop(); } catch (e) { /* noop */ }",
  "      if (activeSession === s) activeSession = null;",
  "    }",
  "  };",
  "",
  // Frame rate is a direct lever on how hard WGC (and therefore the
  // CaptureService broker) is driven. Set by --capture-fps in the main process;
  // null leaves everything alone.
  "  // MediaTrackConstraints lets frameRate be a bare number or",
  "  // { ideal, max, exact }; accept whichever for-web happens to send.",
  "  const frameRateOf = (c) => {",
  "    if (!c || typeof c !== 'object') return 0;",
  "    const fr = c.frameRate;",
  "    if (typeof fr === 'number') return fr;",
  "    if (fr && typeof fr === 'object') return fr.ideal || fr.exact || fr.max || 0;",
  "    return 0;",
  "  };",
  "",
  "  const fpsCap = window.__stoatCaptureFps;",
  "  const withFpsCap = (c) => {",
  "    if (!fpsCap || !c || typeof c !== 'object') return c;",
  "    const next = Object.assign({}, c);",
  "    if (next.video && typeof next.video === 'object') {",
  "      next.video = Object.assign({}, next.video, { frameRate: { ideal: fpsCap, max: fpsCap } });",
  "    } else if (next.video === true) {",
  "      next.video = { frameRate: { ideal: fpsCap, max: fpsCap } };",
  "    }",
  "    return next;",
  "  };",
  "",
  "  // Build a video track fed by native GPU-downscaled capture, in place of",
  "  // whatever Chromium's own capturer produced. Tries MediaStreamTrackGenerator",
  "  // first (verified present on Chromium 148's main thread; unverified on",
  "  // Electron's bundled Chromium at the time this was written -- see the PR",
  "  // description), then falls back to drawing frames onto a canvas and using",
  "  // canvas.captureStream, which costs a GPU upload and a compositor hop but is",
  "  // universally available. Returns null -- meaning 'leave Chromium's own",
  "  // capture running' -- only if neither works.",
  "  //",
  "  // 'generation' is the same token the caller claimed synchronously right",
  "  // after its own getDisplayMedia call resolved (see closeSession above for",
  "  // why that timing matters); it is used here, unchanged, as this video's",
  "  // owner so a stale cleanup can never stop a newer share's native capture.",
  "  const buildVideoTrack = async (state, fps, generation) => {",
  "    const owner = generation;",
  "    let lastWidth = state.width || 1920;",
  "    let lastHeight = state.height || 1080;",
  "    const frameDurationUs = Math.max(1, Math.round(1000000 / (fps || 30)));",
  "",
  "    if (typeof MediaStreamTrackGenerator === 'function') {",
  "      let generator = null;",
  "      try { generator = new MediaStreamTrackGenerator({ kind: 'video' }); } catch (e) { generator = null; }",
  "      if (generator) {",
  "        const writer = generator.writable.getWriter();",
  "        let closed = false;",
  "        const unsubFrame = screenCaptureBridge.onFrame((buf, meta) => {",
  "          if (closed) return;",
  "          lastWidth = meta.width; lastHeight = meta.height;",
  "          let vf = null;",
  "          try {",
  "            vf = new VideoFrame(buf, {",
  "              format: 'NV12',",
  "              codedWidth: meta.width,",
  "              codedHeight: meta.height,",
  "              timestamp: Math.round(performance.now() * 1000),",
  "              duration: frameDurationUs,",
  "            });",
  "          } catch (e) { return; }",
  "          writer.write(vf).catch(() => { /* noop */ }).finally(() => { try { vf.close(); } catch (e) { /* noop */ } });",
  "        });",
  "        // The addon has no way to tell us the window died or capture",
  "        // otherwise failed -- see the long comment on the watchdogs in",
  "        // screenCapture.ts. Once main notices (by polling) and broadcasts",
  "        // inactive, synthesize the 'ended' event ourselves: closing the",
  "        // writer alone does eventually end the track, but dispatching",
  "        // explicitly is what actually drives window.ts's existing",
  "        // screenShare:reacquire path without depending on exactly how fast",
  "        // that natural transition happens.",
  "        const unsubState = screenCaptureBridge.onState((s) => {",
  "          if (!s.active && !closed) {",
  "            closed = true;",
  "            try { generator.dispatchEvent(new Event('ended')); } catch (e) { /* noop */ }",
  "          }",
  "        });",
  "        // A generator track reports no width/height/frameRate by default,",
  "        // which would silently break screenShareScaleFactor's",
  "        // scaleResolutionDownBy math in for-web. Report the true native",
  "        // output size, merged over whatever the real one returns.",
  "        const originalGetSettings = generator.getSettings.bind(generator);",
  "        generator.getSettings = function () {",
  "          return Object.assign({}, originalGetSettings(), {",
  "            width: lastWidth,",
  "            height: lastHeight,",
  "            frameRate: fps,",
  "          });",
  "        };",
  "        // for-web calls this with { frameRate } after publishing -- it is how",
  "        // a quality picked in the share picker reaches the track at all, since",
  "        // the picker resolves *after* capture has already started. A generator",
  "        // track cannot honour it natively and rejecting would break the share,",
  "        // so forward the rate to the native capturer and resolve. Swallowing it",
  "        // outright is what left a 60fps pick stuck at whatever the saved",
  "        // default was.",
  "        generator.applyConstraints = function (c) {",
  "          const next = frameRateOf(c);",
  "          if (next) { try { screenCaptureBridge.setFps(next); } catch (e) { /* noop */ } }",
  "          return Promise.resolve();",
  "        };",
  "        return {",
  "          kind: 'MediaStreamTrackGenerator',",
  "          track: generator,",
  "          cleanup: () => {",
  "            closed = true;",
  "            try { unsubFrame(); } catch (e) { /* noop */ }",
  "            try { unsubState(); } catch (e) { /* noop */ }",
  "            try { writer.close(); } catch (e) { /* noop */ }",
  "            if (owner === currentGeneration) { try { screenCaptureBridge.stop(); } catch (e) { /* noop */ } }",
  "          },",
  "        };",
  "      }",
  "    }",
  "",
  "    if (typeof document !== 'undefined' && typeof VideoFrame === 'function') {",
  "      let canvas = null; let ctx2d = null;",
  "      try {",
  "        canvas = document.createElement('canvas');",
  "        canvas.width = lastWidth; canvas.height = lastHeight;",
  "        ctx2d = canvas.getContext('2d');",
  "      } catch (e) { ctx2d = null; }",
  "      if (ctx2d && canvas.captureStream) {",
  "        const canvasStream = canvas.captureStream(fps || 30);",
  "        const canvasTrack = canvasStream.getVideoTracks()[0];",
  "        if (canvasTrack) {",
  "          let closed = false;",
  "          const unsubFrame = screenCaptureBridge.onFrame((buf, meta) => {",
  "            if (closed) return;",
  "            if (meta.width !== canvas.width || meta.height !== canvas.height) {",
  "              canvas.width = meta.width; canvas.height = meta.height;",
  "            }",
  "            lastWidth = meta.width; lastHeight = meta.height;",
  "            let vf = null;",
  "            try {",
  "              vf = new VideoFrame(buf, {",
  "                format: 'NV12',",
  "                codedWidth: meta.width,",
  "                codedHeight: meta.height,",
  "                timestamp: Math.round(performance.now() * 1000),",
  "                duration: frameDurationUs,",
  "              });",
  "            } catch (e) { return; }",
  "            try { ctx2d.drawImage(vf, 0, 0, canvas.width, canvas.height); } catch (e) { /* noop */ }",
  "            try { vf.close(); } catch (e) { /* noop */ }",
  "          });",
  "          const unsubState = screenCaptureBridge.onState((s) => {",
  "            if (!s.active && !closed) {",
  "              closed = true;",
  "              try { canvasTrack.dispatchEvent(new Event('ended')); } catch (e) { /* noop */ }",
  "            }",
  "          });",
  "          const originalGetSettings = canvasTrack.getSettings.bind(canvasTrack);",
  "          canvasTrack.getSettings = function () {",
  "            return Object.assign({}, originalGetSettings(), {",
  "              width: lastWidth,",
  "              height: lastHeight,",
  "              frameRate: fps,",
  "            });",
  "          };",
  "          canvasTrack.applyConstraints = function (c) {",
  "            const next = frameRateOf(c);",
  "            if (next) { try { screenCaptureBridge.setFps(next); } catch (e) { /* noop */ } }",
  "            return Promise.resolve();",
  "          };",
  "          return {",
  "            kind: 'canvas.captureStream',",
  "            track: canvasTrack,",
  "            cleanup: () => {",
  "              closed = true;",
  "              try { unsubFrame(); } catch (e) { /* noop */ }",
  "              try { unsubState(); } catch (e) { /* noop */ }",
  "              try { canvasTrack.stop(); } catch (e) { /* noop */ }",
  "              if (owner === currentGeneration) { try { screenCaptureBridge.stop(); } catch (e) { /* noop */ } }",
  "            },",
  "          };",
  "        }",
  "      }",
  "    }",
  "",
  "    return null;",
  "  };",
  "",
  "  const original = navigator.mediaDevices.getDisplayMedia.bind(navigator.mediaDevices);",
  "",
  "  navigator.mediaDevices.getDisplayMedia = async function (constraints) {",
  "    // Announce the framerate the page is asking for before calling",
  "    // through to the real getDisplayMedia below -- that call is what",
  "    // triggers setDisplayMediaRequestHandler in the main process, and",
  "    // that handler is never given these constraints, so this is the only",
  "    // way it can see what for-web wanted. Read raw (uncapped)",
  "    // constraints: withFpsCap below exists for the Chromium fallback",
  "    // path only, and the main process applies its own --capture-fps cap",
  "    // on top of whatever we send here (see takeNextRequestedFps in",
  "    // native/screenCapture.ts).",
  "    if (screenCaptureBridge && screenCaptureBridge.setNextFps) {",
  "      let requestedFps = null;",
  "      if (constraints && constraints.video && typeof constraints.video === 'object' && constraints.video.frameRate) {",
  "        const fr = constraints.video.frameRate;",
  "        const ideal = typeof fr === 'object' ? fr.ideal : fr;",
  "        if (typeof ideal === 'number' && ideal > 0) requestedFps = ideal;",
  "      }",
  "      if (requestedFps) {",
  "        try { screenCaptureBridge.setNextFps(requestedFps); } catch (e) { /* noop */ }",
  "      }",
  "    }",
  "",
  "    const capped = withFpsCap(constraints);",
  "    const stream = await original(capped);",
  "",
  "    // Claim this share's ownership generation synchronously, right here,",
  "    // before any further await. By the time 'original' above resolves, main's",
  "    // respondToDisplayMedia (native/window.ts) has ALREADY started this",
  "    // share's native capture -- both startScreenCapture() for video and",
  "    // startForSource() for audio run before it calls back to let this promise",
  "    // resolve -- so the new native capture is live immediately, and until a",
  "    // generation is claimed for it, unowned by the renderer. Every await below",
  "    // (getState(), buildVideoTrack(), buildSession()) is a gap a previous",
  "    // share's own async teardown could land in: the armed re-acquire path",
  "    // (native/window.ts) runs stopAppAudio()/stopScreenCapture() and this",
  "    // request's respondToDisplayMedia in one synchronous main-process block,",
  "    // so the previous share's inactive state is queued before this",
  "    // share's captures start and is only delivered to this renderer after --",
  "    // i.e. squarely inside these awaits -- and the previous share's own video",
  "    // track can fire 'ended' natively at any moment regardless. Claiming the",
  "    // generation here, before any of that can be observed, means every guard",
  "    // below (closeSession's, and buildVideoTrack's cleanup) tests a value that",
  "    // is already final by the time this line finishes -- there is no later",
  "    // point at which a stale share's teardown could still slip in ahead of it.",
  "    const myGeneration = ++generationCounter;",
  "    currentGeneration = myGeneration;",
  "",
  "    // The web client raises the rate again with applyConstraints once the",
  "    // track is published, so cap that too -- on this track only, leaving the",
  "    // camera untouched. Only matters if native video capture below does not",
  "    // end up replacing this track.",
  "    if (fpsCap) {",
  "      const v0 = stream.getVideoTracks()[0];",
  "      if (v0 && v0.applyConstraints) {",
  "        const applyOriginal = v0.applyConstraints.bind(v0);",
  "        v0.applyConstraints = function (c) {",
  "          const next = Object.assign({}, c || {});",
  "          next.frameRate = { ideal: fpsCap, max: fpsCap };",
  "          return applyOriginal(next);",
  "        };",
  "      }",
  "    }",
  "",
  "    // Effective fps for the native path: read from the already-capped",
  "    // constraints (not the raw ones) so --capture-fps composes correctly",
  "    // instead of being bypassed by whatever for-web itself requested.",
  "    let reportFps = fpsCap || 30;",
  "    if (capped && capped.video && typeof capped.video === 'object' && capped.video.frameRate) {",
  "      const ideal = capped.video.frameRate.ideal || capped.video.frameRate;",
  "      if (typeof ideal === 'number' && ideal > 0) reportFps = ideal;",
  "    }",
  "",
  "    let videoCleanup = null;",
  "    let videoState = null;",
  "    if (screenCaptureBridge) {",
  "      try { videoState = await screenCaptureBridge.getState(); } catch (e) { videoState = null; }",
  "    }",
  "    if (videoState && videoState.active) {",
  "      let built = null;",
  "      try { built = await buildVideoTrack(videoState, reportFps, myGeneration); } catch (e) {",
  "        logPage('video: native track build threw, keeping Chromium capture: ' + e);",
  "        built = null;",
  "      }",
  "      if (built) {",
  "        const existingVideo = stream.getVideoTracks();",
  "        for (let i = 0; i < existingVideo.length; i++) {",
  "          try { existingVideo[i].stop(); } catch (e) { /* noop */ }",
  "          stream.removeTrack(existingVideo[i]);",
  "        }",
  "        stream.addTrack(built.track);",
  "        videoCleanup = built.cleanup;",
  "        logPage('video: native GPU capture engaged via ' + built.kind);",
  "      } else {",
  "        // Same generation guard as closeSession and buildVideoTrack's own",
  "        // cleanup: by the time buildVideoTrack's awaits above finish, a newer",
  "        // getDisplayMedia call may already have claimed a later generation,",
  "        // in which case the native capture that is 'active' right now is that",
  "        // newer share's, not this stale attempt's -- stopping it here would",
  "        // be the exact same cross-share kill this file exists to prevent.",
  "        if (myGeneration === currentGeneration) { try { screenCaptureBridge.stop(); } catch (e) { /* noop */ } }",
  "        logPage('video: native capture is active but no output path is available (no MediaStreamTrackGenerator, no canvas.captureStream) -- keeping Chromium capture');",
  "      }",
  "    } else {",
  "      const fallbackReason = (videoState && videoState.reason) || null;",
  "      logPage('video: Chromium capture (native GPU path not engaged for this share' + (fallbackReason ? ': ' + fallbackReason : '') + ')');",
  "    }",
  "",
  "    let audioTrack = null;",
  "    let audioSession = null;",
  "    let state = null;",
  "    try { state = await bridge.getState(); } catch (e) { state = null; }",
  "    if (state && state.active) {",
  "      let s = null;",
  "      try {",
  "        s = await buildSession(state, myGeneration);",
  "        if (!s.track) throw new Error('no audio track produced');",
  "      } catch (e) {",
  "        // Setup failed (or produced no usable track): this share stays",
  "        // silent. It must never fall back to Chromium's own audio track --",
  "        // that is the whole system mix, including any voice call the",
  "        // sharer is on (for-desktop#15) -- so keeping video-only here is",
  "        // deliberate, not a bug.",
  "        console.warn('[stoat] per-app audio setup failed, sharing silently rather than falling back to the system mix', e);",
  "        if (s) closeSession(s);",
  "        // bridge.getState() above said native capture is active for *this*",
  "        // attempt, and this attempt never became the active session, so",
  "        // closeSession above will not have stopped it if a newer share has",
  "        // since taken over -- guard this direct stop() the same way, on the",
  "        // generation claimed at the top of this call, not on session identity.",
  "        if (myGeneration === currentGeneration) { try { bridge.stop(); } catch (e2) { /* noop */ } }",
  "        s = null;",
  "      }",
  "      if (s) {",
  "        // Drop whatever Chromium gave us; it is the whole system mix.",
  "        const existing = stream.getAudioTracks();",
  "        for (let i = 0; i < existing.length; i++) {",
  "          try { existing[i].stop(); } catch (e) { /* noop */ }",
  "          stream.removeTrack(existing[i]);",
  "        }",
  "        stream.addTrack(s.track);",
  "        audioTrack = s.track;",
  "        audioSession = s;",
  "        // Retire the previous session's local resources (AudioContext,",
  "        // worklet graph) now rather than waiting on its own share's",
  "        // eventual 'ended' teardown -- purely for prompt cleanup. Ordering",
  "        // here no longer matters for correctness: 's.generation' was fixed",
  "        // at buildSession() and 'currentGeneration' was already claimed",
  "        // synchronously above, well before this point, so closeSession's",
  "        // bridge.stop() guard is already decided either way.",
  "        const previousSession = activeSession;",
  "        activeSession = s;",
  "        if (previousSession) closeSession(previousSession);",
  "      }",
  "    }",
  "",
  "    // Whichever video track is now on the stream -- Chromium's own, or the",
  "    // one native capture fed -- tears everything down when it ends, exactly",
  "    // once, on every exit path.",
  "    let torndown = false;",
  "    const end = () => {",
  "      if (torndown) return;",
  "      torndown = true;",
  "      try { if (audioTrack) audioTrack.stop(); } catch (e) { /* noop */ }",
  "      // Closes the session *this* getDisplayMedia call captured, not",
  "      // whatever 'activeSession' currently points at -- if a newer share has",
  "      // already superseded it, closeSession is a no-op here (already dead)",
  "      // and never touches the new share's resources.",
  "      closeSession(audioSession);",
  "      try { if (videoCleanup) videoCleanup(); } catch (e) { /* noop */ }",
  "    };",
  "    const video = stream.getVideoTracks()[0];",
  "    if (video) {",
  "      video.addEventListener('ended', end);",
  "      const originalStop = video.stop.bind(video);",
  "      video.stop = function () { originalStop(); end(); };",
  "    }",
  "",
  "    return stream;",
  "  };",
  "})();",
].join("\n");
