/**
 * Source injected into the page's main world.
 *
 * The web app is remote and `contextIsolation` is on, so the preload cannot
 * reach the page's own `navigator.mediaDevices`. We inject this instead: it
 * wraps getDisplayMedia and, when the main process captured a specific
 * application, swaps the system-wide audio track for that app's audio, and
 * swaps a window share's video track for one fed by native GPU-downscaled
 * capture (see native/win-capture and src/native/screenCapture.ts).
 *
 * The web app needs no changes and cannot tell the difference -- it still just
 * receives a MediaStream with one video and one audio track.
 *
 * Written as a plain string (no backticks, no template placeholders) so it
 * survives being handed to executeJavaScript verbatim.
 */
export const APP_AUDIO_PATCH = [
  "(() => {",
  "  if (window.__stoatAppAudioPatched) return;",
  "  const bridge = window.native && window.native.appAudio;",
  "  const screenCaptureBridge = window.native && window.native.screenCapture;",
  "  if (!bridge || !navigator.mediaDevices) return;",
  "  window.__stoatAppAudioPatched = true;",
  "",
  "  // The page console is filtered below error level (see window.ts), so which",
  "  // video path a share took -- and why, on fallback -- is reported through",
  "  // here instead, straight into app-audio.log.",
  "  const logPage = (msg) => {",
  "    try { console.log('[stoat]', msg); } catch (e) { /* noop */ }",
  "    try { if (screenCaptureBridge && screenCaptureBridge.log) screenCaptureBridge.log(msg); } catch (e) { /* noop */ }",
  "  };",
  "",
  "  const WORKLET = [",
  "    'class PcmPlayer extends AudioWorkletProcessor {',",
  "    '  constructor() {',",
  "    '    super();',",
  "    '    this.queue = []; this.offset = 0;',",
  "    '    this.port.onmessage = (e) => {',",
  "    '      if (e.data === 0) { this.queue = []; this.offset = 0; return; }',",
  "    '      this.queue.push(e.data);',",
  "    '      let total = 0;',",
  "    '      for (let i = 0; i < this.queue.length; i++) total += this.queue[i].l.length;',",
  "    '      while (total > 24000 && this.queue.length > 1) {',",
  "    '        total -= this.queue.shift().l.length; this.offset = 0;',",
  "    '      }',",
  "    '    };',",
  "    '  }',",
  "    '  process(inputs, outputs) {',",
  "    '    const out = outputs[0];',",
  "    '    const L = out[0]; const R = out[1] || out[0];',",
  "    '    let i = 0;',",
  "    '    while (i < L.length) {',",
  "    '      if (!this.queue.length) { L.fill(0, i); R.fill(0, i); break; }',",
  "    '      const head = this.queue[0];',",
  "    '      const avail = head.l.length - this.offset;',",
  "    '      const n = Math.min(avail, L.length - i);',",
  "    '      L.set(head.l.subarray(this.offset, this.offset + n), i);',",
  "    '      R.set(head.r.subarray(this.offset, this.offset + n), i);',",
  "    '      i += n; this.offset += n;',",
  "    '      if (this.offset >= head.l.length) { this.queue.shift(); this.offset = 0; }',",
  "    '    }',",
  "    '    return true;',",
  "    '  }',",
  "    '}',",
  "    'registerProcessor(\"pcm-player\", PcmPlayer);'",
  "  ].join('\\n');",
  "",
  "  let ctx = null; let node = null; let dest = null; let unsubscribe = null;",
  "",
  "  const teardown = () => {",
  "    if (unsubscribe) { try { unsubscribe(); } catch (e) { /* noop */ } unsubscribe = null; }",
  "    if (node) { try { node.disconnect(); } catch (e) { /* noop */ } node = null; }",
  "    if (dest) { try { dest.disconnect(); } catch (e) { /* noop */ } dest = null; }",
  "    if (ctx) { const c = ctx; ctx = null; c.close().catch(() => {}); }",
  "    try { bridge.stop(); } catch (e) { /* noop */ }",
  "  };",
  "",
  "  const buildTrack = async (state) => {",
  "    ctx = new AudioContext({ sampleRate: state.sampleRate || 48000 });",
  "    const url = URL.createObjectURL(new Blob([WORKLET], { type: 'application/javascript' }));",
  "    try { await ctx.audioWorklet.addModule(url); } finally { URL.revokeObjectURL(url); }",
  "    node = new AudioWorkletNode(ctx, 'pcm-player', { outputChannelCount: [2] });",
  "    dest = ctx.createMediaStreamDestination();",
  "    node.connect(dest);",
  "    if (ctx.state === 'suspended') { try { await ctx.resume(); } catch (e) { /* noop */ } }",
  "",
  "    unsubscribe = bridge.onChunk((chunk) => {",
  "      if (!node) return;",
  "      const bytes = chunk instanceof Uint8Array ? chunk : new Uint8Array(chunk);",
  "      const frames = (bytes.byteLength >> 1) >> 1;",
  "      if (!frames) return;",
  "      const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);",
  "      const l = new Float32Array(frames);",
  "      const r = new Float32Array(frames);",
  "      for (let i = 0; i < frames; i++) {",
  "        l[i] = view.getInt16(i * 4, true) / 32768;",
  "        r[i] = view.getInt16(i * 4 + 2, true) / 32768;",
  "      }",
  "      node.port.postMessage({ l: l, r: r }, [l.buffer, r.buffer]);",
  "    });",
  "",
  "    return dest.stream.getAudioTracks()[0] || null;",
  "  };",
  "",
  // Frame rate is a direct lever on how hard WGC (and therefore the
  // CaptureService broker) is driven. Set by --capture-fps in the main process;
  // null leaves everything alone.
  "  const fpsCap = window.__stoatCaptureFps;",
  "  const withFpsCap = (c) => {",
  "    if (!fpsCap || !c || typeof c !== 'object') return c;",
  "    const next = Object.assign({}, c);",
  "    if (next.video && typeof next.video === 'object') {",
  "      next.video = Object.assign({}, next.video, { frameRate: { ideal: fpsCap, max: fpsCap } });",
  "    } else if (next.video === true) {",
  "      next.video = { frameRate: { ideal: fpsCap, max: fpsCap } };",
  "    }",
  "    return next;",
  "  };",
  "",
  "  // Build a video track fed by native GPU-downscaled capture, in place of",
  "  // whatever Chromium's own capturer produced. Tries MediaStreamTrackGenerator",
  "  // first (verified present on Chromium 148's main thread; unverified on",
  "  // Electron's bundled Chromium at the time this was written -- see the PR",
  "  // description), then falls back to drawing frames onto a canvas and using",
  "  // canvas.captureStream, which costs a GPU upload and a compositor hop but is",
  "  // universally available. Returns null -- meaning 'leave Chromium's own",
  "  // capture running' -- only if neither works.",
  "  const buildVideoTrack = async (state, fps) => {",
  "    let lastWidth = state.width || 1920;",
  "    let lastHeight = state.height || 1080;",
  "    const frameDurationUs = Math.max(1, Math.round(1000000 / (fps || 30)));",
  "",
  "    if (typeof MediaStreamTrackGenerator === 'function') {",
  "      let generator = null;",
  "      try { generator = new MediaStreamTrackGenerator({ kind: 'video' }); } catch (e) { generator = null; }",
  "      if (generator) {",
  "        const writer = generator.writable.getWriter();",
  "        let closed = false;",
  "        const unsubFrame = screenCaptureBridge.onFrame((buf, meta) => {",
  "          if (closed) return;",
  "          lastWidth = meta.width; lastHeight = meta.height;",
  "          let vf = null;",
  "          try {",
  "            vf = new VideoFrame(buf, {",
  "              format: 'NV12',",
  "              codedWidth: meta.width,",
  "              codedHeight: meta.height,",
  "              timestamp: Math.round(performance.now() * 1000),",
  "              duration: frameDurationUs,",
  "            });",
  "          } catch (e) { return; }",
  "          writer.write(vf).catch(() => { /* noop */ }).finally(() => { try { vf.close(); } catch (e) { /* noop */ } });",
  "        });",
  "        // The addon has no way to tell us the window died or capture",
  "        // otherwise failed -- see the long comment on the watchdogs in",
  "        // screenCapture.ts. Once main notices (by polling) and broadcasts",
  "        // inactive, synthesize the 'ended' event ourselves: closing the",
  "        // writer alone does eventually end the track, but dispatching",
  "        // explicitly is what actually drives window.ts's existing",
  "        // screenShare:reacquire path without depending on exactly how fast",
  "        // that natural transition happens.",
  "        const unsubState = screenCaptureBridge.onState((s) => {",
  "          if (!s.active && !closed) {",
  "            closed = true;",
  "            try { generator.dispatchEvent(new Event('ended')); } catch (e) { /* noop */ }",
  "          }",
  "        });",
  "        // A generator track reports no width/height/frameRate by default,",
  "        // which would silently break screenShareScaleFactor's",
  "        // scaleResolutionDownBy math in for-web. Report the true native",
  "        // output size, merged over whatever the real one returns.",
  "        const originalGetSettings = generator.getSettings.bind(generator);",
  "        generator.getSettings = function () {",
  "          return Object.assign({}, originalGetSettings(), {",
  "            width: lastWidth,",
  "            height: lastHeight,",
  "            frameRate: fps,",
  "          });",
  "        };",
  "        // for-web calls this with { frameRate } after publishing; the",
  "        // native side already owns the rate and a generator track will not",
  "        // honour it, so resolve as a harmless no-op instead of rejecting.",
  "        generator.applyConstraints = function () { return Promise.resolve(); };",
  "        return {",
  "          kind: 'MediaStreamTrackGenerator',",
  "          track: generator,",
  "          cleanup: () => {",
  "            closed = true;",
  "            try { unsubFrame(); } catch (e) { /* noop */ }",
  "            try { unsubState(); } catch (e) { /* noop */ }",
  "            try { writer.close(); } catch (e) { /* noop */ }",
  "            try { screenCaptureBridge.stop(); } catch (e) { /* noop */ }",
  "          },",
  "        };",
  "      }",
  "    }",
  "",
  "    if (typeof document !== 'undefined' && typeof VideoFrame === 'function') {",
  "      let canvas = null; let ctx2d = null;",
  "      try {",
  "        canvas = document.createElement('canvas');",
  "        canvas.width = lastWidth; canvas.height = lastHeight;",
  "        ctx2d = canvas.getContext('2d');",
  "      } catch (e) { ctx2d = null; }",
  "      if (ctx2d && canvas.captureStream) {",
  "        const canvasStream = canvas.captureStream(fps || 30);",
  "        const canvasTrack = canvasStream.getVideoTracks()[0];",
  "        if (canvasTrack) {",
  "          let closed = false;",
  "          const unsubFrame = screenCaptureBridge.onFrame((buf, meta) => {",
  "            if (closed) return;",
  "            if (meta.width !== canvas.width || meta.height !== canvas.height) {",
  "              canvas.width = meta.width; canvas.height = meta.height;",
  "            }",
  "            lastWidth = meta.width; lastHeight = meta.height;",
  "            let vf = null;",
  "            try {",
  "              vf = new VideoFrame(buf, {",
  "                format: 'NV12',",
  "                codedWidth: meta.width,",
  "                codedHeight: meta.height,",
  "                timestamp: Math.round(performance.now() * 1000),",
  "                duration: frameDurationUs,",
  "              });",
  "            } catch (e) { return; }",
  "            try { ctx2d.drawImage(vf, 0, 0, canvas.width, canvas.height); } catch (e) { /* noop */ }",
  "            try { vf.close(); } catch (e) { /* noop */ }",
  "          });",
  "          const unsubState = screenCaptureBridge.onState((s) => {",
  "            if (!s.active && !closed) {",
  "              closed = true;",
  "              try { canvasTrack.dispatchEvent(new Event('ended')); } catch (e) { /* noop */ }",
  "            }",
  "          });",
  "          const originalGetSettings = canvasTrack.getSettings.bind(canvasTrack);",
  "          canvasTrack.getSettings = function () {",
  "            return Object.assign({}, originalGetSettings(), {",
  "              width: lastWidth,",
  "              height: lastHeight,",
  "              frameRate: fps,",
  "            });",
  "          };",
  "          canvasTrack.applyConstraints = function () { return Promise.resolve(); };",
  "          return {",
  "            kind: 'canvas.captureStream',",
  "            track: canvasTrack,",
  "            cleanup: () => {",
  "              closed = true;",
  "              try { unsubFrame(); } catch (e) { /* noop */ }",
  "              try { unsubState(); } catch (e) { /* noop */ }",
  "              try { canvasTrack.stop(); } catch (e) { /* noop */ }",
  "              try { screenCaptureBridge.stop(); } catch (e) { /* noop */ }",
  "            },",
  "          };",
  "        }",
  "      }",
  "    }",
  "",
  "    return null;",
  "  };",
  "",
  "  const original = navigator.mediaDevices.getDisplayMedia.bind(navigator.mediaDevices);",
  "",
  "  navigator.mediaDevices.getDisplayMedia = async function (constraints) {",
  "    const capped = withFpsCap(constraints);",
  "    const stream = await original(capped);",
  "",
  "    // The web client raises the rate again with applyConstraints once the",
  "    // track is published, so cap that too -- on this track only, leaving the",
  "    // camera untouched. Only matters if native video capture below does not",
  "    // end up replacing this track.",
  "    if (fpsCap) {",
  "      const v0 = stream.getVideoTracks()[0];",
  "      if (v0 && v0.applyConstraints) {",
  "        const applyOriginal = v0.applyConstraints.bind(v0);",
  "        v0.applyConstraints = function (c) {",
  "          const next = Object.assign({}, c || {});",
  "          next.frameRate = { ideal: fpsCap, max: fpsCap };",
  "          return applyOriginal(next);",
  "        };",
  "      }",
  "    }",
  "",
  "    // Effective fps for the native path: read from the already-capped",
  "    // constraints (not the raw ones) so --capture-fps composes correctly",
  "    // instead of being bypassed by whatever for-web itself requested.",
  "    let reportFps = fpsCap || 30;",
  "    if (capped && capped.video && typeof capped.video === 'object' && capped.video.frameRate) {",
  "      const ideal = capped.video.frameRate.ideal || capped.video.frameRate;",
  "      if (typeof ideal === 'number' && ideal > 0) reportFps = ideal;",
  "    }",
  "",
  "    let videoCleanup = null;",
  "    let videoState = null;",
  "    if (screenCaptureBridge) {",
  "      try { videoState = await screenCaptureBridge.getState(); } catch (e) { videoState = null; }",
  "    }",
  "    if (videoState && videoState.active) {",
  "      let built = null;",
  "      try { built = await buildVideoTrack(videoState, reportFps); } catch (e) {",
  "        logPage('video: native track build threw, keeping Chromium capture: ' + e);",
  "        built = null;",
  "      }",
  "      if (built) {",
  "        const existingVideo = stream.getVideoTracks();",
  "        for (let i = 0; i < existingVideo.length; i++) {",
  "          try { existingVideo[i].stop(); } catch (e) { /* noop */ }",
  "          stream.removeTrack(existingVideo[i]);",
  "        }",
  "        stream.addTrack(built.track);",
  "        videoCleanup = built.cleanup;",
  "        logPage('video: native GPU capture engaged via ' + built.kind);",
  "      } else {",
  "        try { screenCaptureBridge.stop(); } catch (e) { /* noop */ }",
  "        logPage('video: native capture is active but no output path is available (no MediaStreamTrackGenerator, no canvas.captureStream) -- keeping Chromium capture');",
  "      }",
  "    } else {",
  "      logPage('video: Chromium capture (native GPU path not engaged for this share)');",
  "    }",
  "",
  "    let audioTrack = null;",
  "    let state = null;",
  "    try { state = await bridge.getState(); } catch (e) { state = null; }",
  "    if (state && state.active) {",
  "      let track = null;",
  "      try { track = await buildTrack(state); } catch (e) {",
  "        console.warn('[stoat] per-app audio setup failed, keeping system audio', e);",
  "        teardown();",
  "        track = null;",
  "      }",
  "      if (track) {",
  "        // Drop whatever Chromium gave us; it is the whole system mix.",
  "        const existing = stream.getAudioTracks();",
  "        for (let i = 0; i < existing.length; i++) {",
  "          try { existing[i].stop(); } catch (e) { /* noop */ }",
  "          stream.removeTrack(existing[i]);",
  "        }",
  "        stream.addTrack(track);",
  "        audioTrack = track;",
  "      } else {",
  "        teardown();",
  "      }",
  "    }",
  "",
  "    // Whichever video track is now on the stream -- Chromium's own, or the",
  "    // one native capture fed -- tears everything down when it ends, exactly",
  "    // once, on every exit path.",
  "    let torndown = false;",
  "    const end = () => {",
  "      if (torndown) return;",
  "      torndown = true;",
  "      try { if (audioTrack) audioTrack.stop(); } catch (e) { /* noop */ }",
  "      teardown();",
  "      try { if (videoCleanup) videoCleanup(); } catch (e) { /* noop */ }",
  "    };",
  "    const video = stream.getVideoTracks()[0];",
  "    if (video) {",
  "      video.addEventListener('ended', end);",
  "      const originalStop = video.stop.bind(video);",
  "      video.stop = function () { originalStop(); end(); };",
  "    }",
  "",
  "    return stream;",
  "  };",
  "})();",
].join("\n");
