/**
 * Source injected into the page's main world.
 *
 * Enables Discord-style click-to-join for voice channels. When a user clicks
 * a voice channel in the sidebar, this script intercepts the click, allows
 * navigation to happen, and then automatically clicks the "Join" button
 * in the channel header.
 *
 * When already in a call (including PIP mode), clicking a different voice
 * channel will first disconnect from the current call, then auto-join the new one.
 *
 * Clicking the same channel while connected is a no-op.
 *
 * The web app needs no changes and cannot tell the difference.
 *
 * Written as a plain string (no backticks, no template placeholders) so it
 * survives being handed to executeJavaScript verbatim.
 */
export const VOICE_PATCH = [
  "(() => {",
  "  try {",
  "  if (window.__stoatVoicePatch) return;",
  "  window.__stoatVoicePatch = true;",
  "",
  "  const LOG = '[stoat-voice]';",
  "  let joinAbort = null;",
  "  let currentChannelHref = null;",
  "",
  "  function log() {",
  "    console.log(LOG, Array.prototype.slice.call(arguments).join(' '));",
  "  }",
  "",
  "  function isVoiceChannel(el) {",
  "    try {",
  "      if (!el || el.nodeType !== 1) return false;",
  '      if (el.tagName !== "A") return false;',
  '      const href = el.getAttribute("href") || "";',
  '      if (!href.includes("/server/") || !href.includes("/channel/")) return false;',
  '      return (el.textContent || "").includes("headset_mic");',
  "    } catch (e) { return false; }",
  "  }",
  "",
  "  function isInCall() {",
  "    try {",
  '      const icons = document.querySelectorAll("span.material-symbols-outlined");',
  "      for (const icon of icons) {",
  '        if ((icon.textContent || "").trim() === "call_end") return true;',
  "      }",
  '      const audioEls = document.querySelectorAll("audio");',
  "      for (const a of audioEls) {",
  "        if (a.srcObject || a.src) return true;",
  "      }",
  "      return false;",
  "    } catch (e) { return false; }",
  "  }",
  "",
  "  function clickDisconnectButton() {",
  "    try {",
  '      const icons = document.querySelectorAll("span.material-symbols-outlined");',
  "      for (const icon of icons) {",
  '        if ((icon.textContent || "").trim() === "call_end") {',
  "          let target = icon.parentElement;",
  "          for (let i = 0; i < 10 && target; i++) {",
  '            if (target.tagName === "BUTTON" || target.querySelector("md-ripple")) {',
  '              log("clicking Disconnect button");',
  "              target.click();",
  "              return true;",
  "            }",
  "            target = target.parentElement;",
  "          }",
  "          return false;",
  "        }",
  "      }",
  "      return false;",
  "    } catch (e) { return false; }",
  "  }",
  "",
  "  async function clickJoinButton(signal) {",
  "    let attempt = 0;",
  "    const maxAttempts = 10;",
  "",
  "    while (attempt < maxAttempts) {",
  "      if (signal && signal.aborted) return false;",
  "",
  "      await new Promise((r) => setTimeout(r, attempt === 0 ? 500 : 1000));",
  "",
  "      if (signal && signal.aborted) return false;",
  "",
  '      log("searching for Join button (attempt", attempt + 1, ")");',
  "",
  "      // Strategy 1: Find voice_chat Material icon and click its parent with md-ripple",
  '      const icons = document.querySelectorAll("span.material-symbols-outlined");',
  "      for (const icon of icons) {",
  '        if ((icon.textContent || "").trim() === "voice_chat") {',
  "          let target = icon;",
  "          for (let i = 0; i < 8; i++) {",
  "            target = target.parentElement;",
  "            if (!target) break;",
  '            if (target.querySelector("md-ripple")) {',
  '              log("found Join button via voice_chat icon");',
  "              target.click();",
  "              return true;",
  "            }",
  "          }",
  "          const fallback = icon.parentElement?.parentElement?.parentElement;",
  "          if (fallback) { fallback.click(); return true; }",
  "        }",
  "      }",
  "",
  "      // Strategy 2: Find by localized text",
  '      const all = document.querySelectorAll("p, span, div");',
  "      for (const el of all) {",
  '        const txt = (el.textContent || "").trim();',
  '        if (txt === "Iniciar chamada" || txt === "Start call" || txt === "Join") {',
  '          log("found Join button via text:", txt);',
  "          let target = el.parentElement;",
  "          for (let i = 0; i < 5; i++) {",
  "            if (!target) break;",
  '            if (target.querySelector("md-ripple") || target.tagName === "BUTTON") {',
  "              target.click();",
  "              return true;",
  "            }",
  "            target = target.parentElement;",
  "          }",
  "          el.parentElement?.click();",
  "          return true;",
  "        }",
  "      }",
  "",
  "      attempt++;",
  "    }",
  "",
  "    return false;",
  "  }",
  "",
  "  function attachClickListener(el) {",
  "    if (el.__stoatVoiceListener) return;",
  "    el.__stoatVoiceListener = true;",
  "",
  '    el.addEventListener("click", () => {',
  "      if (joinAbort) {",
  '        log("cancelling previous join attempt");',
  "        joinAbort.abort();",
  "      }",
  "",
  "      joinAbort = new AbortController();",
  "      const signal = joinAbort.signal;",
  "",
  '      log(">>> voice channel clicked:", el.getAttribute("href"));',
  "",
  "      async function run() {",
  "        await new Promise((r) => setTimeout(r, 500));",
  "        if (signal.aborted) return;",
  "",
  "        const href = el.getAttribute('href');",
  "        if (currentChannelHref && href === currentChannelHref) {",
  '          log("already connected to this channel, skipping");',
  "          return;",
  "        }",
  "",
  "        if (isInCall()) {",
  '          log("in a call, disconnecting first...");',
  "          currentChannelHref = null;",
  "          if (clickDisconnectButton()) {",
  "            for (let i = 0; i < 15; i++) {",
  "              if (signal.aborted) return;",
  "              await new Promise((r) => setTimeout(r, 500));",
  "              if (!isInCall()) break;",
  "            }",
  "            await new Promise((r) => setTimeout(r, 1000));",
  "          }",
  "        }",
  "",
  "        if (signal.aborted) return;",
  "",
  "        if (await clickJoinButton(signal)) {",
  "          currentChannelHref = el.getAttribute('href');",
  "        }",
  "      }",
  "",
  "      run().catch(() => {});",
  "    });",
  "  }",
  "",
  "  function processElement(root) {",
  "    if (!root || !root.querySelectorAll) return;",
  '    const links = root.querySelectorAll("a");',
  "    let found = 0;",
  "    for (const link of links) {",
  "      if (isVoiceChannel(link)) {",
  "        attachClickListener(link);",
  "        found++;",
  "      }",
  "    }",
  "    if (found > 0) log('attached listeners to', found, 'voice channel(s)');",
  "  }",
  "",
  "  const observer = new MutationObserver((mutations) => {",
  "    for (const m of mutations) {",
  "      for (const node of m.addedNodes) {",
  "        if (node.nodeType === 1) processElement(node);",
  "      }",
  "    }",
  "  });",
  "",
  "  function init() {",
  "    if (!document.body) { setTimeout(init, 200); return; }",
  "    processElement(document.body);",
  "    observer.observe(document.body, { childList: true, subtree: true });",
  '    log("observer active");',
  "  }",
  "",
  "  init();",
  "  } catch (e) { console.error(LOG, 'FATAL:', e); }",
  "})();",
].join("\n");
